---
title: Planets Of The Universe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  page:
    title: page
    output: true
baseurl: "/planets-of-the-universe"
exclude:
- README.md
permalink: pretty
